{% set name = "cons" %}
{% set version = "0.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cons-{{ version }}.tar.gz
  sha256: 0a96cd2abd6a9f494816c1272cf5583a960041750c2d7a48eeeccd47ce369dfd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77.0.0
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - logical-unification >=0.4.0

test:
  imports:
    - cons
  commands:
    - pip check
    - python -c "from importlib.metadata import version; print(version('{{ name }}'))"
    - python -c "from importlib.metadata import version; print(version('{{ name }}'))" | grep {{ version }}
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/pythological/python-cons
  summary: An implementation of Lisp/Scheme-like cons in Python.
  license: LGPL-3.0-only
  license_file: LICENSE.txt
  dev_url: https://github.com/pythological/python-cons

extra:
  recipe-maintainers:
    - maresb
    - brandonwillard
