{% set version = "0.4.7" %}

package:
  name: cons
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/cons/cons-{{ version }}.tar.gz
  sha256: 0a96cd2abd6a9f494816c1272cf5583a960041750c2d7a48eeeccd47ce369dfd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - logical-unification >=0.4.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - cons

about:
  home: https://github.com/pythological/python-cons
  license: LGPL-3.0-only
  summary: An implementation of Lisp/Scheme-like cons in Python.
  license_file: LICENSE.txt
  dev_url: https://github.com/pythological/python-cons

extra:
  recipe-maintainers:
    - maresb
    - brandonwillard
